const LoginFormTypes = {
    TOGGLE_LOGIN_FORM: 'TOGGLE_LOGIN_FORM',
    UPDATE_LOGIN_EMAIL: "UPDATE_LOGIN_EMAIL",
    UPDATE_LOGIN_PASSWORD: "UPDATE_LOGIN_PASSWORD",
    UPDATE_ERROR: "UPDATE_ERROR"
}

export default LoginFormTypes;