const newUserDataTypes = {
    UPDATE_FIRST_NAME: "UPDATE_FIRST_NAME",
    UPDATE_LAST_NAME: "UPDATE_LAST_NAME",
    UPDATE_COUNTRY: "UPDATE_COUNTRY",
    UPDATE_PHONE: "UPDATE_PHONE",
    UPDATE_CONTACT_EMAIL: "UPDATE_CONTACT_EMAIL"
}

export default newUserDataTypes;